name: Release Binaries

on:
  push:
    tags:
      - 'v*.*.*'

# MODIFIED: Enforce a consistent shell for all steps in all jobs.
# This prevents platform-specific issues between PowerShell and Bash.
defaults:
  run:
    shell: bash

jobs:
  build:
    name: Build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      # MODIFIED: Add flags to make npm more robust in CI environments.
      - name: Install dependencies
        run: npm ci --no-audit --no-progress

      - name: Build project
        run: npm run build

      - name: Get version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF_NAME#v}" >> $GITHUB_OUTPUT

      - name: Prepare Binary (Linux)
        if: runner.os == 'Linux'
        run: |
          npm run build:standalone:linux
          mv dist/template-engine-linux dist/template-engine-v${{ steps.get_version.outputs.VERSION }}-linux

      - name: Prepare Binary (macOS)
        if: runner.os == 'macOS'
        run: |
          npm run build:standalone:macos
          mv dist/template-engine-macos dist/template-engine-v${{ steps.get_version.outputs.VERSION }}-macos

      - name: Prepare Binary (Windows)
        if: runner.os == 'Windows'
        run: |
          npm run build:standalone:windows
          mv dist/template-engine-win.exe dist/template-engine-v${{ steps.get_version.outputs.VERSION }}-win.exe

      - name: Upload binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: binary-${{ runner.os }}
          path: dist/template-engine-v${{ steps.get_version.outputs.VERSION }}-${{ runner.os == 'Windows' && 'win.exe' || (runner.os | lower) }}
          if-no-files-found: error # Fail the build if the binary is missing

  publish-release:
    name: Publish Release
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write

    steps:
      - name: Download all binary artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist

      - name: List downloaded files for verification
        run: ls -R dist

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          name: "Release ${{ github.ref_name }}"
          generate_release_notes: true
          # Upload all files from the subdirectories in 'dist'
          files: dist/*/*
